CREATE TABLE command_history_import_batch (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  file_name VARCHAR(255) NOT NULL,
  schema_version VARCHAR(32) NOT NULL,
  export_id VARCHAR(64) NOT NULL,
  exporting_environment_id VARCHAR(128) NOT NULL,
  exporting_environment_name VARCHAR(128) NOT NULL,
  exporting_base_url VARCHAR(512),
  exported_at TIMESTAMP WITH TIME ZONE NOT NULL,
  exported_by VARCHAR(128) NOT NULL,
  record_count INTEGER NOT NULL,
  imported_count INTEGER NOT NULL DEFAULT 0,
  skipped_duplicate_count INTEGER NOT NULL DEFAULT 0,
  failed_count INTEGER NOT NULL DEFAULT 0,
  package_checksum VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  failure_reason TEXT,
  imported_by VARCHAR(128) NOT NULL,
  imported_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_command_history_import_batch_imported_at
  ON command_history_import_batch (imported_at DESC);

CREATE TABLE imported_command_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_batch_id BIGINT NOT NULL REFERENCES command_history_import_batch(id) ON DELETE CASCADE,
  original_source_environment_id VARCHAR(128) NOT NULL,
  original_source_environment_name VARCHAR(128) NOT NULL,
  direct_source_environment_id VARCHAR(128) NOT NULL,
  direct_source_environment_name VARCHAR(128) NOT NULL,
  origin_execution_id BIGINT NOT NULL,
  command TEXT NOT NULL,
  target_snapshot TEXT NOT NULL,
  status VARCHAR(32) NOT NULL,
  duration_ms BIGINT,
  source VARCHAR(32) NOT NULL,
  operator_name VARCHAR(128) NOT NULL,
  executed_at TIMESTAMP WITH TIME ZONE NOT NULL,
  output_size_bytes BIGINT NOT NULL DEFAULT 0,
  output_truncated BOOLEAN NOT NULL DEFAULT FALSE,
  output_sha256 VARCHAR(128) NOT NULL,
  error_message TEXT,
  risk_level VARCHAR(32) NOT NULL DEFAULT 'ALLOW',
  risk_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  record_checksum VARCHAR(128) NOT NULL,
  duplicate_key VARCHAR(512) NOT NULL,
  provenance_chain TEXT NOT NULL,
  local_target_id BIGINT,
  imported_by VARCHAR(128) NOT NULL,
  imported_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uk_imported_command_history_duplicate_key
  ON imported_command_history (duplicate_key);
CREATE INDEX idx_imported_command_history_executed_at
  ON imported_command_history (executed_at DESC);
CREATE INDEX idx_imported_command_history_import_batch
  ON imported_command_history (import_batch_id);
CREATE INDEX idx_imported_command_history_original_source
  ON imported_command_history (original_source_environment_id);

CREATE TABLE imported_command_output_chunk (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  imported_history_id BIGINT NOT NULL REFERENCES imported_command_history(id) ON DELETE CASCADE,
  sequence INTEGER NOT NULL,
  content TEXT NOT NULL,
  size_bytes INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  UNIQUE (imported_history_id, sequence)
);

CREATE INDEX idx_imported_command_output_chunk_history
  ON imported_command_output_chunk (imported_history_id, sequence);
